---
# tasks file for "arcfg.cli.gnome_extensions_cli" role
- name: "Install dependencies"
  kewlfft.aur.aur:
    name: "{{ gnome_extensions_cli_packages }}"
    use: "paru"
    extra_args: "--needed"
  # Avoid use local Python venv
  environment:
    PATH: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
