---
# tasks file for "arcfg.kernels.linux_zen" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ linux_zen_packages }}"
    extra_args: "--needed"
  register: "kernel_zen" # noqa: var-naming[no-role-prefix]
