---
# tasks file for "arcfg.desktop.kotami" role
- name: "Install dependencies"
  kewlfft.aur.aur:
    name: "{{ kotami_packages }}"
    use: "paru"
    extra_args: "--needed"
  # Avoid use local Python venv
  environment:
    PATH: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"

- name: "Create Kotami system dirs"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    mode: "u=rwx,g=rx,o=rx"
    owner: "greeter"
    group: "greeter"
  loop:
    - "/var/lib/kotami"
    - "/var/log/kotami"

- name: "Copy config files"
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode if item.mode is defined else 'u=rw,g=r,o=r' }}"
    owner: "greeter"
    group: "greeter"
  loop:
    - src: "usr/bin/kotami-greeter"
      dest: "/usr/bin/kotami-greeter"
      mode: "u=rwx,g=rx,o=rx"
    - src: "etc/greetd/niri-run-astal-greet.kdl"
      dest: "/etc/greetd/niri-run-astal-greet.kdl"
      mode: "u=rw,g=r,o=r"
    - src: "etc/greetd/config.toml"
      dest: "/etc/greetd/config.toml"
      mode: "u=rw,g=r,o=r"

# NOTE: workaround to keep current role path
# - name: "Set current role path"
#   ansible.builtin.set_fact:
#     kotami_role_path: "{{ role_path }}"

# - name: "Create a symbolic links to kotami config dirs"
#   ansible.builtin.include_role:
#     name: "arcfg.internal.linkcfg"
#   vars:
#     linkcfg_items:
#       - src: "{{ kotami_role_path }}/files/home/user/.config/kotami"
#         dest: "{{ ansible_user_dir }}/.config/kotami"
#         mode: "u=rwx,g=rx,o=rx"

# - name: "Set dconf keys"
#   community.general.dconf:
#     key: "{{ item.key }}"
#     value: "{{ item.value if item.value is defined }}"
#     state: "{{ item.state if item.state is defined else 'present' }}"
#   loop:
#     - key: ""
#       value: ""

- name: "arcfg.desktop.kotami : Execute post roles" # noqa: name[casing]
  ansible.builtin.include_role:
    allow_duplicates: false
    name: "{{ role_item.role }}"
  loop_control:
    loop_var: "role_item"
  loop: "{{ kotami_post_tasks_roles }}"
