---
# tasks file for "arcfg.apps.geary" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ geary_packages }}"
    extra_args: "--needed"

- name: "Set dconf keys"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value if item.value is defined else '' }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
  loop:
    - key: "/org/gnome/Geary/run-in-background"
      value: "true"
