---
# tasks file for "arcfg.themes.console" role
- name: "Convert HEX to decimal arrays"
  set_fact:
    "color_scheme_color_list":
      - "{{ color_scheme_data.background }}"
      - "{{ color_scheme_data.color_02 }}"
      - "{{ color_scheme_data.color_03 }}"
      - "{{ color_scheme_data.color_04 }}"
      - "{{ color_scheme_data.color_05 }}"
      - "{{ color_scheme_data.color_06 }}"
      - "{{ color_scheme_data.color_07 }}"
      - "{{ color_scheme_data.color_08 }}"
      - "{{ color_scheme_data.color_09 }}"
      - "{{ color_scheme_data.color_10 }}"
      - "{{ color_scheme_data.color_11 }}"
      - "{{ color_scheme_data.color_12 }}"
      - "{{ color_scheme_data.color_13 }}"
      - "{{ color_scheme_data.color_14 }}"
      - "{{ color_scheme_data.color_15 }}"
      - "{{ color_scheme_data.color_16 }}"
    color_scheme_color_red: "{{ [] }}"
    color_scheme_color_grn: "{{ [] }}"
    color_scheme_color_blu: "{{ [] }}"

- name: "Extract RGB components"
  loop: "{{ color_scheme_color_list }}"
  set_fact:
    color_scheme_color_red: "{{ color_scheme_color_red + [item[1:3] | int(base=16)] }}"
    color_scheme_color_grn: "{{ color_scheme_color_grn + [item[3:5] | int(base=16)] }}"
    color_scheme_color_blu: "{{ color_scheme_color_blu + [item[5:7] | int(base=16)] }}"

- name: "Compose kernel parameters"
  set_fact:
    "color_scheme_vt": "vt.default_red={{ color_scheme_color_red | join(',') }} vt.default_grn={{ color_scheme_color_grn | join(',') }} vt.default_blu={{ color_scheme_color_blu
      | join(',') }}"

- name: "Print <color_scheme_color_red> from arcfg.themes.console"
  ansible.builtin.debug:
    var: color_scheme_vt
