---
# tasks file for "arcfg.apps.gnome_calendar" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ gnome_calendar_packages }}"
    extra_args: "--needed"

- name: Set a default handlers for known MIME-types
  community.general.gio_mime:
    mime_type: "{{ item }}"
    handler: "org.gnome.Calendar.desktop"
  loop:
    - "text/calendar"
