---
# tasks file for "arcfg.de.kotami_niri" role
- name: "Create a niri user config directory"
  ansible.builtin.file:
    path: "~/.config/niri"
    state: "directory"
    mode: "u=rwx,g=rx,o=rx"

- name: "Copy the 'niri-tablet-mode' helper"
  become: true
  ansible.builtin.copy:
    src: "usr/local/bin/niri-tablet-mode"
    dest: "/usr/local/bin/niri-tablet-mode"
    mode: "u=rwx,g=rx,o=rx"
  when: "system_type == 'transformer' or system_type == 'tablet'"

- name: "Update user config file"
  ansible.builtin.template:
    src: "home/user/.config/niri/config.kdl.j2"
    dest: "~/.config/niri/config.kdl"
    mode: "u=rw,g=r,o=r"

- name: "Set dconf keys"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value if item.value is defined else '' }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
  loop:
    # Hide GTK window control buttons
    - key: "/org/gnome/desktop/wm/preferences/button-layout"
      value: "''"
