---
# tasks file for "arcfg.hardware.pipewire" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ pipewire_packages }}"
    extra_args: "--needed --ask 4" # undocumented option (--ask BITMASK) https://unix.stackexchange.com/a/584001
