---
# tasks file for "arcfg.display_manager.gdm" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ gdm_packages }}"
    extra_args: "--needed"

# - name: "Wayland enable"
#   become: true
#   lineinfile:
#     path: "/etc/gdm/custom.conf"
#     regexp: "^#WaylandEnable=false"
#     line: "WaylandEnable=true"
#   when: "wayland_compositor is defined"

- name: "Enable GDM service"
  become: true
  ansible.builtin.systemd:
    name: "gdm.service"
    enabled: true
