---
# tasks file for "arcfg.gnome.gnome_appearance" role
# - name: "Install dependencies"
#   become: true
#   community.general.pacman:
#     name: "{{ gnome_appearance_packages }}"
#     extra_args: "--needed"

- name: "Set appearance"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/desktop/interface/color-scheme"
      value: "{{ \"'prefer-dark'\" if ui_prefer_dark is defined and ui_prefer_dark else \"'default'\" }}"
    - key: "/org/gnome/desktop/interface/accent-color"
      value: "'blue'"

    # GTK3 Theme
    - key: "/org/gnome/desktop/interface/gtk-theme"
      value: "{{ \"'adw-gtk3-dark'\" if ui_prefer_dark is defined and ui_prefer_dark else \"'adw-gtk3'\" }}"

    # Icon
    - key: "/org/gnome/desktop/interface/icon-theme"
      value: "{{ \"'Papirus-Dark'\" if ui_prefer_dark is defined and ui_prefer_dark else \"'Papirus-Light'\" }}"

- name: "arcfg.gnome.gnome_appearance : Execute post roles" # noqa: name[casing]
  ansible.builtin.include_role:
    allow_duplicates: false
    name: "{{ role_item.role }}"
  loop_control:
    loop_var: "role_item"
  loop: "{{ gnome_appearance_post_roles }}"
