---
# defaults file for "arcfg.gnome_shell_extensions.space_bar" role
#
# A list of roles that must be executed after all tasks for this role are completed.
space_bar_post_roles: []
#  - role: "arcfg.gnome_shell_extensions.example"
