---
# tasks file for "arcfg.gnome_gio_mime.gapless" role
- name: Set a default handlers for known MIME-types
  community.general.gio_mime:
    mime_type: "{{ item }}"
    handler: "com.github.neithern.g4music.desktop"
  loop:
    - "audio/x-vorbis+ogg"
    - "audio/wav"
    - "audio/webm"
    - "audio/x-aac"
    - "audio/x-aiff"
    - "audio/x-ape"
    - "audio/x-flac"
    - "audio/x-it"
    - "audio/x-m4a"
    - "audio/x-m4b"
    - "audio/x-matroska"
    - "audio/x-mod"
    - "audio/x-mp1"
    - "audio/x-mp2"
    - "audio/x-mp3"
    - "audio/x-mpg"
    - "audio/x-mpeg"
    - "audio/x-ms-asf"
    - "audio/x-ms-asx"
    - "audio/x-ms-wax"
    - "audio/x-ms-wma"
    - "audio/x-musepack"
    - "audio/x-opus+ogg"
    - "audio/x-pn-aiff"
    - "audio/x-pn-au"
    - "audio/x-pn-realaudio"
    - "audio/x-pn-realaudio-plugin"
    - "audio/x-pn-wav"
    - "audio/x-pn-windows-acm"
    - "audio/x-realaudio"
    - "audio/x-real-audio"
    - "audio/x-s3m"
    - "audio/x-sbc"
    - "audio/x-shorten"
    - "audio/x-speex"
    - "audio/x-stm"
    - "audio/x-tta"
    - "audio/x-wav"
    - "audio/x-wavpack"
    - "audio/x-vorbis"
    - "audio/x-xm"
    - "audio/x-mpegurl"
    - "audio/x-scpls"
