---
# tasks file for "arcde.hirigami.hyprland" role
- name: "Install dependencies"
  become: true
  become_user: "aur_builder"
  kewlfft.aur.aur:
    name: "{{ hyprland_packages }}"
    use: "paru"
  # Avoid use local Python venv
  environment:
    PATH: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"

- name: "Include Hyprland config tasks"
  ansible.builtin.include_tasks: "hypr-config.yml"

# - name: "Copy the 'hyprland' helper"
#   become: true
#   ansible.builtin.copy:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     mode: "{{ item.mode if item.mode is defined else 'u=rw,g=r,o=r' }}"
#   loop:
#     - src: "etc/profile.d/00-hyprland.sh"
#       dest: "/etc/profile.d/00-hyprland.sh"
#       mode: "u=rw,g=r,o=r"

# # NOTE: workaround to keep current role path
# - name: "Set current role path"
#   ansible.builtin.set_fact:
#     hyprland_role_path: "{{ role_path }}"

# - name: "Create a symbolic links to hyprland config dirs"
#   ansible.builtin.include_role:
#     name: "arcfg.internal.linkcfg"
#   vars:
#     linkcfg_items:
#       - src: "{{ hyprland_role_path }}/files/home/user/.config/hyprland"
#         dest: "{{ ansible_user_dir }}/.config/hyprland"
#         mode: "u=rwx,g=rx,o=rx"

# - name: "Apply the 'hyprland' config templates"
#   ansible.builtin.template:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     mode: "{{ item.mode if item.mode is defined else 'u=rw,g=r,o=r' }}"
#   loop:
#     - src: "home/user/.config/hyprland/config.j2"
#       dest: "~/.config/hyprland/config"
#       mode: "u=rw,g=r,o=r"

# - name: "Set dconf keys"
#   community.general.dconf:
#     key: "{{ item.key }}"
#     value: "{{ item.value if item.value is defined else '' }}"
#     state: "{{ item.state if item.state is defined else 'present' }}"
#   loop:
#     - key: ""
#       value: ""
