---
# tasks file for "arcfg.apps.eog" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ eog_packages }}"
    extra_args: "--needed"

- name: "Set dconf keys"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value if item.value is defined else '' }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
  loop:
    - key: "/org/gnome/eog/ui/sidebar"
      value: "false"

- name: Set a default handlers for known MIME-types
  community.general.gio_mime:
    mime_type: "{{ item }}"
    handler: "org.gnome.eog.desktop"
  loop:
    - "image/jpeg"
    - "image/bmp"
    - "image/gif"
    - "image/jpg"
    - "image/jxl"
    - "image/pjpeg"
    - "image/png"
    - "image/tiff"
    - "image/webp"
    - "image/x-bmp"
    - "image/x-gray"
    - "image/x-icb"
    - "image/x-ico"
    - "image/x-png"
    - "image/x-portable-anymap"
    - "image/x-portable-bitmap"
    - "image/x-portable-graymap"
    - "image/x-portable-pixmap"
    - "image/x-xbitmap"
    - "image/x-xpixmap"
    - "image/x-pcx"
    - "image/svg+xml"
    - "image/svg+xml-compressed"
    - "image/vnd.wap.wbmp"
    - "image/x-icns"
