---
# tasks file for "arcfg.internal.color_scheme" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ color_scheme_packages }}"
    extra_args: "--needed"

- name: "Clone Gogh repository"
  ansible.builtin.git:
    repo: "https://github.com/Gogh-Co/Gogh.git"
    dest: "~/.cache/Gogh"
    version: "{{ color_scheme_gogh_version }}"
    update: false

- name: "Include selected color scheme data"
  ansible.builtin.include_vars:
    file: "~/.cache/Gogh/themes/{{ color_scheme_name }}.yml"
    name: color_scheme_data
