---
# tasks file for "arcfg.env.editor" role
- name: "Install default cli text editor"
  ansible.builtin.include_role:
    name: "arcfg.cli.{{ editor_name | replace('-', '_') }}"

- name: "Install visudo text editor"
  ansible.builtin.include_role:
    name: "arcfg.cli.{{ editor_sudo_name | replace('-', '_') }}"
  when: "editor_sudo_name is defined and editor_sudo_name != editor_name"

- name: "Remove the profile.d script file created by Archi installer"
  become: true
  ansible.builtin.file:
    path: "/etc/profile.d/env_editor.sh"
    state: absent

- name: "Create the $EDITOR variable helper"
  become: true
  ansible.builtin.template:
    src: "etc/profile.d/10-editor.sh.j2"
    dest: "/etc/profile.d/10-editor.sh"
    mode: "u=rw,g=r,o=r"
