---
# tasks file for "arcfg.gnome_gio_mime.vivaldi" role
- name: Set a default handlers for known MIME-types
  community.general.gio_mime:
    mime_type: "{{ item }}"
    handler: "org.gnome.TextEditor.desktop"
  loop:
    - "x-scheme-handler/http"
    - "x-scheme-handler/https"
