---
# tasks file for "arcfg.apps.extension_manager" role
- name: "Install dependencies"
  kewlfft.aur.aur:
    name: "{{ extension_manager_packages }}"
    use: "paru"
    extra_args: "--needed"
  # Avoid use local Python venv
  environment:
    PATH: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
