---
# tasks file for "arcfg.gnome_shell_extensions.tray_icons_reloaded" role

# GNOME Shell extension which bring back Tray Icons to top panel
# https://github.com/martinpl/tray-icons-reloaded
- name: "Install and enable 'Tray Icons Reloaded' extension"
  ansible.builtin.include_role:
    name: "arcfg.internal.gnome_shell_extension_install"
  vars:
    # https://extensions.gnome.org/extension/2890/tray-icons-reloaded/
    gnome_shell_extension_install_id: "2890"

- name: "Configure 'Tray Icons Reloaded'"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value if item.value is defined else '' }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
  loop:
    - key: "/org/gnome/shell/extensions/trayIconsReloaded/tray-margin-left"
      value: "4"
    - key: "/org/gnome/shell/extensions/trayIconsReloaded/tray-margin-right"
      value: "4"
    - key: "/org/gnome/shell/extensions/trayIconsReloaded/icon-size"
      value: "20"
    - key: "/org/gnome/shell/extensions/trayIconsReloaded/icon-margin-horizontal"
      value: "0"
    - key: "/org/gnome/shell/extensions/trayIconsReloaded/icon-padding-horizontal"
      value: "8"
