---
galaxy_info:
  description: "Must have desktop applications"

  # Platforms is a list of platforms, and each platform has a name and a list of versions.
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"

# List your role dependencies here, one per line. Be sure to remove the '[]' above,
# if you add dependencies to this list.
dependencies:
  - role: arcfg.internal.python_psutil
  - role: arcfg.env.xdg_terminal_exec
  - role: arcfg.env.user_dirs
  - role: arcfg.apps.nautilus
  - role: arcfg.apps.gnome_text_editor
  - role: arcfg.apps.extension_manager
  # TODO: Select browser
  - role: arcfg.apps.vivaldi
  - role: arcfg.gnome.gnome_browser_extension_chromium
    vars:
      gnome_browser_extension_chromium_browser: "vivaldi"
  # PIM
  - role: arcfg.apps.geary
  - role: arcfg.apps.gnome_calendar
  - role: arcfg.apps.gnome_contacts
  - role: arcfg.apps.endeavour
  - role: arcfg.apps.gnome_weather
  # Media
  - role: arcfg.apps.loupe
  - role: arcfg.apps.eog
  - role: arcfg.apps.celluloid
  - role: arcfg.apps.gapless
  - role: arcfg.apps.shortwave
  - role: arcfg.apps.blanket

  - role: arcfg.apps.authenticator
