---
# tasks file for "arcfg.gnome_shell_extensions.space_bar" role

# GNOME Shell extension that shows workspaces buttons in top panel
# https://github.com/christopher-l/space-bar
- name: "Install and enable 'Space Bar' extension"
  ansible.builtin.include_role:
    name: "arcfg.internal.gnome_shell_extension_install"
  vars:
    # https://extensions.gnome.org/extension/5090/space-bar/
    gnome_shell_extension_install_id: "5090"

- name: "Configure 'Space Bar'"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value if item.value is defined else '' }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
  loop:
    - key: "/org/gnome/shell/extensions/space-bar/behavior/toggle-overview"
      value: "false"
    # Switch workspaces with scroll wheel handled by "dash-to-panel" extension
    # Disabled to avoid duplicate events
    - key: "/org/gnome/shell/extensions/space-bar/behavior/scroll-wheel"
      value: "'disabled'"
