---
# tasks file for "arcfg.pm.paru" role
- name: "Check that the Paru already installed"
  ansible.builtin.stat:
    path: "/usr/bin/paru"
  register: "paru_stat_result"

- name: "Get Paru sources from AUR" # noqa: latest
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/paru-bin.git"
    dest: "/tmp/paru-bin"
  when: "not paru_stat_result.stat.exists"
  register: "paru_get_result"

- name: "Make and install Paru"
  ansible.builtin.shell: "makepkg -si --noconfirm"
  args:
    chdir: "/tmp/paru-bin"
    executable: "/bin/bash"
  register: "paru_install_result"
  when: "paru_get_result is changed"
  changed_when: "paru_install_result.rc is defined and paru_install_result.rc == 0"

- name: "Remove Paru sources"
  ansible.builtin.file:
    state: "absent"
    path: "/tmp/paru-bin"
  when: "paru_get_result is changed"
