---
# tasks file for "arcfg.gnome.keyboard" role

# Use CapsLock to change keyboard layout
# Use "Scroll Lock" led to indicate alternative keyboard layout
# Use Right Alt as Compose button
- name: "Configure xkb options"
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['grp:caps_toggle', 'grp_led:scroll', 'compose:ralt']"

- name: "Configure keyboard input sources"
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    # Dirty hack to render value with paired outer square brackets '[('xkb', 'us'), ('xkb', '<layout>')]'
    value: "{{ [('xkb', 'us'), ('xkb', '<layout>')] | replace('<layout>', keyboard_layout) | string }}"
  when: "keyboard_layout is defined"

- name: "Keys setup"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value if item.value is defined else '' }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
  loop:
    - key: "/org/gnome/settings-daemon/plugins/media-keys/volume-step"
      value: "5"

- name: "Custom keybindings"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value if item.value is defined else '' }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
  loop:
    # List of keybindings
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/annotator/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/annotator-use-clipboard/']"
    # Annotator
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/annotator/binding"
      value: "'<Super>Print'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/annotator/command"
      value: "'annotator'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/annotator/name"
      value: "'Start Annotator'"
    # Annotate image from clipboard
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/annotator-use-clipboard/binding"
      value: "'<Shift><Super>Print'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/annotator-use-clipboard/command"
      value: "'annotator --use-clipboard'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/annotator-use-clipboard/name"
      value: "'Annotate image from clipboard'"
