---
# tasks file for "arcfg.shell.bash" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ bash_packages }}"
    extra_args: "--needed"

# NOTE: workaround to keep current role path
- name: "Set current role path"
  ansible.builtin.set_fact:
    bash_role_path: "{{ role_path }}"

- name: "Copy the bootstrap files"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode if item.mode is defined else 'u=rw,g=r,o=r' }}"
  loop:
    - src: "home/user/.bash_profile"
      dest: "~/.bash_profile"
      mode: "u=rw,g=r,o=r"
    - src: "home/user/.bashrc"
      dest: "~/.bashrc"
      mode: "u=rw,g=r,o=r"

- name: "Create a symbolic links to bash config dirs"
  ansible.builtin.include_role:
    name: "arcfg.internal.linkcfg"
  vars:
    linkcfg_items:
      - src: "{{ bash_role_path }}/files/home/user/.config/bash"
        dest: "{{ ansible_user_dir }}/.config/bash"
        mode: "u=rwx,g=rx,o=rx"
      - src: "{{ bash_role_path }}/files/home/user/.config/sheldon/bash"
        dest: "{{ ansible_user_dir }}/.config/sheldon/bash"
        mode: "u=rwx,g=rx,o=rx"
