---
# tasks file for "arcfg.apps.celluloid" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ celluloid_packages }}"
    extra_args: "--needed"

# # NOTE: workaround to keep current role path
# - name: "Set current role path"
#   ansible.builtin.set_fact:
#     celluloid_role_path: "{{ role_path }}"

# - name: "Create a symbolic links to celluloid config dirs"
#   ansible.builtin.include_role:
#     name: "arcfg.internal.linkcfg"
#   vars:
#     linkcfg_items:
#       - src: "{{ celluloid_role_path }}/files/home/user/.config/celluloid"
#         dest: "{{ ansible_user_dir }}/.config/celluloid"
#         mode: "u=rwx,g=rx,o=rx"

- name: "Set dconf keys"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value if item.value is defined else '' }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
  loop:
    - key: "/io/github/celluloid-player/celluloid/always-open-new-window"
      value: "true"
    - key: "/io/github/celluloid-player/celluloid/last-folder-enable"
      value: "true"

- name: Set a default handlers for known MIME-types
  community.general.gio_mime:
    mime_type: "{{ item }}"
    handler: "io.github.celluloid_player.Celluloid.desktop"
  loop:
    - "video/x-ogm+ogg"
    - "video/3gp"
    - "video/3gpp"
    - "video/3gpp2"
    - "video/divx"
    - "video/dv"
    - "video/fli"
    - "video/flv"
    - "video/mp2t"
    - "video/mp4"
    - "video/mp4v-es"
    - "video/mpeg"
    - "video/mpeg-system"
    - "video/msvideo"
    - "video/ogg"
    - "video/quicktime"
    - "video/vnd.mpegurl"
    - "video/vnd.rn-realvideo"
    - "video/webm"
    - "video/x-avi"
    - "video/x-flc"
    - "video/x-fli"
    - "video/x-flv"
    - "video/x-m4v"
    - "video/x-matroska"
    - "video/x-mpeg"
    - "video/x-mpeg-system"
    - "video/x-mpeg2"
    - "video/x-ms-asf"
    - "video/x-ms-wm"
    - "video/x-ms-wmv"
    - "video/x-ms-wmx"
    - "video/x-msvideo"
    - "video/x-nsv"
    - "video/x-theora"
    - "video/x-theora+ogg"
