---
# tasks file for "arcfg.env.path" role
- name: "Create '~/.local/bin' directory"
  ansible.builtin.file:
    path: "~/.local/bin"
    state: "directory"
    mode: "u=rwx,g=rx,o=rx"

- name: "Copy the $PATH variable helper"
  become: true
  ansible.builtin.copy:
    src: "etc/profile.d/00.path.sh"
    dest: "/etc/profile.d/00.path.sh"
    mode: "u=rw,g=r,o=r"
