---
# tasks file for "arcfg.gnome_gio_mime.eog" role
- name: Set a default handlers for known MIME-types
  community.general.gio_mime:
    mime_type: "{{ item }}"
    handler: "org.gnome.eog.desktop"
  loop:
    - "image/jpeg"
    - "image/bmp"
    - "image/gif"
    - "image/jpg"
    - "image/jxl"
    - "image/pjpeg"
    - "image/png"
    - "image/tiff"
    - "image/webp"
    - "image/x-bmp"
    - "image/x-gray"
    - "image/x-icb"
    - "image/x-ico"
    - "image/x-png"
    - "image/x-portable-anymap"
    - "image/x-portable-bitmap"
    - "image/x-portable-graymap"
    - "image/x-portable-pixmap"
    - "image/x-xbitmap"
    - "image/x-xpixmap"
    - "image/x-pcx"
    - "image/svg+xml"
    - "image/svg+xml-compressed"
    - "image/vnd.wap.wbmp"
    - "image/x-icns"
