---
# tasks file for "arcfg.apps.annotator" role
- name: "Install dependencies"
  become: true
  become_user: "aur_builder"
  kewlfft.aur.aur:
    name: "{{ annotator_packages }}"
    use: "paru"
  # Avoid use local Python venv
  environment:
    PATH: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"


- name: "Set dconf keys"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value if item.value is defined else '' }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
  loop:
    - key: "/com/github/phase1geo/annotator/dash-pattern"
      value: "'none'"
    - key: "/org/gnome/desktop/notifications/application/com-github-phase1geo-annotator/enable"
      value: "true"
