---
# tasks file for "arcfg.apps.annotator" role
- name: "Install dependencies"
  kewlfft.aur.aur:
    name: "{{ annotator_packages }}"
    use: "paru"
    extra_args: "--needed"

- name: "Set dconf keys"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value if item.value is defined }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
  loop:
    - key: "/com/github/phase1geo/annotator/dash-pattern"
      value: "'none'"
    - key: "/org/gnome/desktop/notifications/application/com-github-phase1geo-annotator/enable"
      value: "true"
