---
# tasks file for "arcfg.gnome_shell_extensions.arch_update" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ arch_update_packages }}"
    extra_args: "--needed"

# Update indicator for Arch Linux and GNOME Shell
# https://github.com/RaphaelRochet/arch-update
- name: "Install and enable 'Arch Update' extension"
  ansible.builtin.include_role:
    name: "arcfg.internal.gnome_shell_extension_install"
  vars:
    # https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/
    gnome_shell_extension_install_id: "1010"

- name: "Configure 'Arch Update' extension"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value if item.value is defined else '' }}"
    state: "{{ item.state if item.state is defined else 'present' }}"
  loop:
    - key: "/org/gnome/shell/extensions/arch-update/show-count"
      value: "false"
    - key: "/org/gnome/shell/extensions/arch-update/always-visible"
      value: "false"
    - key: "/org/gnome/shell/extensions/arch-update/use-buildin-icons"
      value: "false"
    - key: "/org/gnome/shell/extensions/arch-update/notify"
      value: "true"
    - key: "/org/gnome/shell/extensions/arch-update/howmuch"
      value: "0"
    - key: "/org/gnome/shell/extensions/arch-update/strip-versions-in-notification"
      value: "false"
      # gnome-terminal -- /bin/sh -c "sudo pacman -Syu ; echo Done - Press enter to exit; read _"
    - key: "/org/gnome/shell/extensions/arch-update/update-cmd"
      value: "'{{ arch_update_command[xdg_terminal_exec_name] }}'"
