---
# tasks file for "arcfg.gnome_gio_mime.celluloid" role
- name: Set a default handlers for known MIME-types
  community.general.gio_mime:
    mime_type: "{{ item }}"
    handler: "io.github.celluloid_player.Celluloid.desktop"
  loop:
    - "video/x-ogm+ogg"
    - "video/3gp"
    - "video/3gpp"
    - "video/3gpp2"
    - "video/divx"
    - "video/dv"
    - "video/fli"
    - "video/flv"
    - "video/mp2t"
    - "video/mp4"
    - "video/mp4v-es"
    - "video/mpeg"
    - "video/mpeg-system"
    - "video/msvideo"
    - "video/ogg"
    - "video/quicktime"
    - "video/vnd.mpegurl"
    - "video/vnd.rn-realvideo"
    - "video/webm"
    - "video/x-avi"
    - "video/x-flc"
    - "video/x-fli"
    - "video/x-flv"
    - "video/x-m4v"
    - "video/x-matroska"
    - "video/x-mpeg"
    - "video/x-mpeg-system"
    - "video/x-mpeg2"
    - "video/x-ms-asf"
    - "video/x-ms-wm"
    - "video/x-ms-wmv"
    - "video/x-ms-wmx"
    - "video/x-msvideo"
    - "video/x-nsv"
    - "video/x-theora"
    - "video/x-theora+ogg"
