---
# tasks file for "arcfg.display_manager.uwsm" role
- name: "Install dependencies"
  become: true
  become_user: "aur_builder"
  kewlfft.aur.aur:
    name: "{{ uwsm_packages }}"
    use: "paru"
  # Avoid use local Python venv
  environment:
    PATH: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"

- name: "arcfg.display_manager.uwsm : Execute post roles" # noqa: name[casing]
  ansible.builtin.include_role:
    allow_duplicates: false
    name: "{{ role_item.role }}"
  loop_control:
    loop_var: "role_item"
  loop: "{{ uwsm_post_roles }}"
