---
# tasks file for "arcfg.env.xdg_terminal_exec" role
- name: "Install dependencies"
  become: true
  become_user: "aur_builder"
  kewlfft.aur.aur:
    name: "{{ xdg_terminal_exec_packages }}"
    use: "paru"

- name: "Install default terminal emulator"
  ansible.builtin.include_role:
    name: "arcfg.apps.{{ xdg_terminal_exec_name | replace('-', '_') }}"

# https://gitlab.freedesktop.org/Vladimir-csp/xdg-terminal-exec#default-terminal-execution-specification
- name: "Generate ~/.config/xdg-terminals.list"
  ansible.builtin.template:
    src: "home/user/.config/xdg-terminals.list.j2"
    dest: "~/.config/xdg-terminals.list"
    mode: "u=rw,g=r,o=r"
