---
# tasks file for "arcfg.boot.grub" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ grub_packages }}"
    extra_args: "--needed"

- name: "Update /etc/default/grub"
  become: true
  ansible.builtin.template:
    src: "etc/default/grub.j2"
    dest: "/etc/default/grub"
    mode: "0644"
  register: "grub_config_update"

- name: "Remove GRUB loading messages"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/grub.d/10_linux"
    regexp: "^\\s*echo\\s+'\\$\\(echo \"\\$message\" \\| grub_quote\\)'$"
    state: "absent"
  register: "grub_config_10_linux_update"

- name: "Add class to UEFI menuentry"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/grub.d/30_uefi-firmware"
    regexp: "^\\s*menuentry '\\$LABEL' \\\\\\$menuentry_id_option 'uefi-firmware' {$"
    line: "\t\tmenuentry '$LABEL' --class efi \\$menuentry_id_option 'uefi-firmware' {"
  register: "grub_config_30_uefi_update"

- name: "Update GRUB config"
  become: true
  ansible.builtin.shell: "grub-mkconfig -o /esp/GRUB/grub/grub.cfg"
  args:
    executable: "/usr/bin/bash"
  register: "grub_mkconfig_result"
  when: |-
    grub_config_update is changed
    or grub_config_10_linux_update is changed
    or grub_config_30_uefi_update is changed
    or (grub_theme_update is defined and grub_theme_update is changed)
    or (kernel_latest is defined and kernel_latest is changed)
    or (kernel_lts is defined and kernel_lts is changed)
    or (kernel_lqx is defined and kernel_lqx is changed)
    or (kernel_zen is defined and kernel_zen is changed)
  changed_when: "grub_mkconfig_result.rc == 0"
