---
# tasks file for "arcfg.apps.kitty" role
- name: "Install dependencies"
  become: true
  community.general.pacman:
    name: "{{ kitty_packages }}"
    extra_args: "--needed"

# NOTE: workaround to keep current role path
- name: "Set current role path"
  ansible.builtin.set_fact:
    kitty_role_path: "{{ role_path }}"

- name: "Create a symbolic links to kitty config dirs"
  ansible.builtin.include_role:
    name: "arcfg.internal.linkcfg"
  vars:
    linkcfg_items:
      - src: "{{ kitty_role_path }}/files/home/user/.config/kitty/kitty.conf"
        dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
        mode: "u=rwx,g=rx,o=rx"
